POST http://localhost:8000/_allauth/app/v1/auth/login HTTP/1.1
content-type: application/json

{
    "username": "sbulutgenc",
    "password": "Ss7206584*"
}

### Get Auth Session
GET http://localhost:8000/_allauth/app/v1/auth/session HTTP/1.1
content-type: application/json

X-Session-Token: es3xcimfjdhbjvy4azwica03k3f1mxec
