###
POST http://localhost:8000/_allauth/app/v1/auth/signup HTTP/1.1
content-type: application/json

{
  "email": "testuser1@domain.org",
  "username": "testuser1",
  "password": "Ss7206584*"
}


###
POST http://localhost:8000/_allauth/app/v1/auth/login HTTP/1.1
content-type: application/json

{
  "username": "sbulutgenc",
  "password": "Ss7206584*"
}

###
POST http://localhost:8000/api/posts/ HTTP/1.1
content-type: application/json
X-Session-Token:khmko456qby1lxtavm3f5ul55udkgvdn

{
  "title": "Post titletd",
  "body": "post content",
  "categoryId": "1"
}

###
GET http://localhost:8000/api/posts/ HTTP/1.1
content-type: application/json
X-Session-Token:khmko456qby1lxtavm3f5ul55udkgvdn


###
GET http://localhost:8000/api/posts/60 HTTP/1.1
content-type: application/json

###
DELETE http://localhost:8000/api/posts/70 HTTP/1.1
content-type: application/json


###
POST http://localhost:8000/api/categories/ HTTP/1.1
content-type: application/json

{
  "title": "Category title"
}


###
GET http://localhost:8000/api/categories/ HTTP/1.1
content-type: application/json

###
DELETE http://localhost:8000/api/categories/16 HTTP/1.1
content-type: application/json

### 
GET http://localhost:8000/_allauth/app/v1/auth/session
content-type:application/json
X-Session-Token:r9s64sd3spnyn805jg1g56qjy5nz1y02

###
DELETE http://localhost:8000/_allauth/app/v1/auth/session
X-Session-Token:r9s64sd3spnyn805jg1g56qjy5nz1y02

