# Generated by Django 6.0.1 on 2026-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="info",
            field=models.JSONField(
                blank=True,
                help_text="Profile Information",
                null=True,
                verbose_name="Info",
            ),
        ),
    ]
