# Generated by Django 6.0.1 on 2026-01-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='dexcription',
            new_name='description',
        ),
    ]
