# Generated by Django 6.0.1 on 2026-01-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_dexcription_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Slug', max_length=255, verbose_name='Slıg'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Slug', max_length=255, verbose_name='Slıg'),
        ),
    ]
