# Generated by Django 6.0.1 on 2026-01-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_slug_alter_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                editable=False,
                help_text="Slug",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
