# Generated by Django 6.0.8 on 2026-10-06 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="User's first name.", max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text="User's last name.", max_length=255, verbose_name='Last Name')),
                ('info', models.JSONField(blank=True, help_text='User information in JSON format.', null=True, verbose_name='Info')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
